### ISSUE TITLE
Getting Error 503 or null response while uploading thumbnail to api

### ISSUE THREAD

**Issue by rohity821** [VineAPI/VineAPI#2]
I am a newbie to iOS programming 

I am trying to upload to the API endpoints given here. first i tried to login i am successful in it i logined and got key and userid then i tried to upload thumbnail and video to the endpoints given but it is giving me some weird errors like 503, network connection was lost or response: (null)... if i coment some headers the response changes from server i am using AFNetworking framework

Snipplet of CODE:- 
AFHTTPClient *httpClient = [[AFHTTPClient alloc]initWithBaseURL:[NSURL URLWithString:@"https://media.vineapp.com"]];
    NSLog(@"%@",@"Uploading data");

```
//        Upload Image
NSMutableURLRequest *request = [
                                httpClient multipartFormRequestWithMethod:@"PUT" path:@"/upload/thumbs/img.jpg" parameters:nil constructingBodyWithBlock:^(id<AFMultipartFormData> formData)
                                {
                                    [formData appendPartWithFileData:imgData name:@"thumb1" fileName:@"img" mimeType:@"image/jpeg"];
                                    NSLog(@"Uploading");

                                }
                                ];
 //[request setValue:@"media.vineapp.com" forHTTPHeaderField:@"Host"];
[request setValue:@"keep-alive" forHTTPHeaderField:@"Proxy-Connection"];
[request setValue:@"image/jpeg" forHTTPHeaderField:@"Content-Type"];
[request setValue:@"ios/1.4.7" forHTTPHeaderField:@"X-Vine-Client"];
//[request setValue:[NSString stringWithFormat:@"%d",[imgData length]] forHTTPHeaderField:@"Content-Length"];
[request setValue:@"en;q=1, fr;q=0.9, de;q=0.8, ja;q=0.7, nl;q=0.6, it;q=0.5" forHTTPHeaderField:@"Accept-Language"];
//[request setValue:@"*/*" forHTTPHeaderField:@"Accept"];
[request setValue:_key forHTTPHeaderField:@"vine-session-id"];
[request setValue:@"gzip, deflate" forHTTPHeaderField:@"Accept-Encoding"];
[request setValue:@"keep-alive" forHTTPHeaderField:@"Connection"];
[request setValue:@"iphone/1.4.7 (iPhone; iOS 7.0.0; Scale/2.00)" forHTTPHeaderField:@"User-Agent"];

AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
NSLog(@"Tst1");
[
 operation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
     NSLog(@"Uploaded:Sent %lld of %lld bytes", totalBytesWritten, totalBytesExpectedToWrite);
     NSLog(@"Key is : %@",_key);
 }
 ];

[operation setCompletionBlockWithSuccess:^(AFHTTPRequestOperation *operation, id responseObject)
 {
     NSLog(@"response: %@",[NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingAllowFragments error:nil]);
 }
                                 failure:^(AFHTTPRequestOperation *operation, NSError *error)
 {
     NSLog(@"Upload Failed");

     NSLog(@"error: %@", [operation error]);
 }
 ];


[httpClient enqueueHTTPRequestOperation:operation];
NSLog(@"Operation start");
```

in this the response is null if i uncomment the subsequent header then it says network connection was lost.

Kindly help me out tell me does this PUT requests work or not. i am struck thanks in advance

**Comment by vietphu** [comment]
To upload video to Vine, plz following the following three step:
1. Upload video: PUT with https://media.vineapp.com/upload/videos/1.3.1.mp4
In this step you will got video url in response header
2. Upload video thumbnail: PUT with https://media.vineapp.com/upload/thumbs/1.3.1.mp4.jpg
In this step you will got video thumbnail url in response header
3. Post video with: POST https://api.vineapp.com/posts
param: 
- "videoUrl": video url in step 1
- "ThumbUrl": thumbnail url in step 2
- "channelId":
- "Description":
- "Entities":

More detail plz check: http://www.codeproject.com/Articles/893709/Discovering-the-Vine-API
I tried and it's success!

Good luck!

**Comment by ghost** [comment]
@Dinh Viet Phu, are you Vietnamese?

## 

Nguyễn Văn Bảo Anh

**Comment by vietphu** [comment]
@nguyenvanbaoanh ah,yeah. :dart:

**Comment by ghost** [comment]
oh yeah! please add my skype: nvbaoanh
thanks!

## 

Nguyễn Văn Bảo Anh

**Comment by thisbejim** [comment]
Any one able to upload videos at the moment? I can successfully upload a video but then it seems to be deleted when I go to the permalink.

**Comment by golches** [comment]
any php example i am stucked in "You must provide the Content-Length HTTP header." after login and try sending the thumbnail

**Comment by rohity821** [comment]
closing this issue.
